# Generated by Django 4.2.4 on 2023-08-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
