# Generated by Django 4.2.4 on 2023-08-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=45)),
                ('address', models.TextField()),
            ],
        ),
    ]
