# Generated by Django 4.2.4 on 2023-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='card_id',
            new_name='cart_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
