# Generated by Django 4.2.4 on 2023-08-21 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_delete_usertransactionmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_useraddress_userbankaccount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBankAccountModel',
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
    ]
