# Generated by Django 4.2.4 on 2023-08-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeModel',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=50)),
                ('designation', models.CharField(max_length=44)),
            ],
        ),
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('section', models.CharField(max_length=34)),
                ('attendence', models.BooleanField()),
                ('hw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='studentInfoModel',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=50)),
                ('payment', models.IntegerField()),
                ('section', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(max_length=45)),
                ('mother_name', models.CharField(max_length=45)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='teacherInfoModel',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=50)),
                ('subject', models.CharField(max_length=45)),
                ('salary', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='managerModel',
            fields=[
                ('employeemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_app.employeemodel')),
                ('take_hire', models.BooleanField()),
                ('take_interview', models.BooleanField()),
                ('take_promotion', models.BooleanField()),
            ],
            bases=('my_app.employeemodel',),
        ),
        migrations.CreateModel(
            name='MeModel',
            fields=[
                ('friendmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_app.friendmodel')),
            ],
            bases=('my_app.friendmodel',),
        ),
    ]
