# Generated by Django 4.2.4 on 2023-08-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendmodel',
            old_name='attendence',
            new_name='attendance',
        ),
        migrations.DeleteModel(
            name='MeModel',
        ),
        migrations.CreateModel(
            name='MeModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('my_app.friendmodel',),
        ),
    ]
