# Generated by Django 4.2.4 on 2023-08-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_person_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=50)),
                ('section', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=45)),
                ('who_take_book', models.IntegerField()),
                ('student_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.student')),
            ],
        ),
    ]
