# Generated by Django 4.2.4 on 2023-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_student_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=50)),
                ('cur_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.TextField(max_length=50)),
                ('subject', models.CharField(max_length=45)),
                ('salary', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('student_user', models.ManyToManyField(to='my_app.studentinfo')),
            ],
        ),
    ]
