# Generated by Django 4.2.4 on 2023-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_studentinfo_teacherinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='my_app.teacherinfo'),
        ),
    ]
