# Generated by Django 4.2.4 on 2023-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_teacherinfo_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='student_user',
            field=models.ManyToManyField(to='my_app.studentinfo'),
        ),
    ]
