# Generated by Django 4.2.4 on 2023-08-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_attendence_friendmodel_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_type', models.CharField(max_length=20)),
                ('passport_number', models.IntegerField()),
                ('page', models.IntegerField()),
                ('validity', models.IntegerField()),
                ('regional_office', models.CharField(max_length=45)),
                ('person_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.person')),
            ],
        ),
    ]
