# Generated by Django 4.2.4 on 2023-08-09 20:06

import book_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=40)),
                ('catagory', models.CharField(choices=[('western', 'Western'), ('revenge', 'Revenge'), ('spaghetti_western', 'Spaghetti Western'), ('action', 'Action'), ('drama', 'Drama'), ('historical', 'Historical'), ('adventure', 'Adventure'), ('crime', 'Crime'), ('thriller', 'Thriller'), ('noir', 'Noir'), ('romance', 'Romance'), ('neo_western', 'Neo-Western'), ('martial_arts', 'Martial Arts'), ('ensemble_cast', 'Ensemble Cast'), ('fantasy', 'Fantasy'), ('comedy', 'Comedy'), ('redemption', 'Redemption'), ('classic', 'Classic'), ('biographical', 'Biographical'), ('tragedy', 'Tragedy')], max_length=75)),
                ('first_published', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('isbn', models.CharField(blank=True, default=book_app.models.create_new_ref_number, editable=False, max_length=75, unique=True)),
            ],
        ),
    ]
